language: node_js
sudo: required
node_js:
- 10.14.2
cache:
  directories:
  - node_modules
branches:
  only:
  - hexo-master-build
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo-cli
install:
- npm install
- npm install hexo-deployer-git --save
- npm install hexo-generator-sitemap --save
- npm install hexo-generator-baidu-sitemap --save
- npm install hexo-renderer-jade hexo-renderer-stylus --save

before_script:
script:
after_script:
- hexo deploy
- cd ./public
- git init
- git config user.name "micrqwe"
- git config user.email "micrqwe@163.com"
- git add --all .
- git commit --allow-empty -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://${token}@github.com/micrqwe/micrqwe.github.io.git  master:master
